#!/bin/bash

ite829x=""
configPath="/home/${USER}/.local/share/"
configFile="ite-829x.conf"

ite829xFind() {
	if [ "$(which ite-829x)" != "" ]; then
		ite829x=$(which ite-829x)
	elif [ "$(ls ite-829x)" != "" ]; then
		ite829x="./ite-829x"
	fi

	if [ "${ite829x}" = "" ]; then
		echo "Unable to find ite-829x binaries"
		exit 1
	fi
}

kblSave() {
	cfg=""

	leds=""
	keys=({0..19} {32..43} {45..51} {64..83} {96..108} {110..115} 128 {130..147} {160..165} {169..179})
	if [ "${red}" != "" ] && [ "${green}" != "" ] && [ "${blue}" != "" ]; then
		for key in ${keys[@]}; do
			leds="${leds}led ${key} ${red} ${green} ${blue}\n"
		done
	fi


	cfg="reset\nbrightness+speed ${brightness} ${speed}\neffects ${effect}\n${leds}"

	echo -e ${cfg} > ${configPath}${configFile}
}

kblLoad() {
	brightnessspeed=$(cat ${configPath}${configFile} | grep 'brightness+speed' | sed 's/brightness+speed//' | xargs)
	IFS=' ' read -ra brightnessspeed <<< "${brightnessspeed}"
	brightness=${brightnessspeed[0]}
	speed=${brightnessspeed[1]}
	effect=$(cat ${configPath}${configFile} | grep 'effects' | sed 's/effects//' | xargs)
	colorrgb=$(cat ${configPath}${configFile} | grep 'led' | head -1 | sed 's/led//' | xargs)
	IFS=' ' read -ra colorrgb <<< "${colorrgb}"
	red=${colorrgb[1]}
	green=${colorrgb[2]}
	blue=${colorrgb[3]}
}

kblSet() {
	i=1;
	for arg in "${@}"
	do
		j=$((i + 1))
		case "${!i}" in
			-bs | --brightness) brightness=${!j};;
			-s | --speed) speed=${!j};;
			-e | --effect) effect=${!j};;
			-r | --red) red=${!j};;
			-g | --green) green=${!j};;
			-b | --blue) blue=${!j};;
		esac
		i=$((i + 1));
	done

	cfg=""

	leds=""
	keys=({0..19} {32..43} {45..51} {64..83} {96..108} {110..115} 128 {130..147} {160..165} {169..179})
	if [ "${red}" != "" ] && [ "${red}" != "" ] && [ "${blue}" != "" ]; then
		for key in ${keys[@]}; do
			leds="${leds}led ${key} ${red} ${green} ${blue}\n"
		done
	fi

	echo -e ${leds}

	if [ "${effect}" = "7" ]; then
		cfg="reset\nbrightness+speed ${brightness} ${speed}\n"
	else
		cfg="reset\nbrightness+speed ${brightness} ${speed}\neffects ${effect}\n"
	fi

	if [ "${effect}" = "7" ]; then
		sudo ${ite829x} << LEDs
			$(echo -e ${cfg}${leds})
LEDs
	else
		sudo ${ite829x} << LEDs
			$(echo -e ${cfg})
LEDs
	fi
}

kblToggle() {
	i=1;
	for arg in "${@}"
	do
		j=$((i + 1))
		case "${!i}" in
			-bs | --brightness) brightnessa=${!j};;
			-s | --speed) speeda=${!j};;
			-e | --effect) effecta=${!j};;
			-c | --color) color=${!j};;
		esac
		i=$((i + 1));
	done

	if [ "${brightnessa}" = 'up' ] && [ "${brightness}" != 4 ]; then
		brightness=$((brightness + 1))
	elif [ "${brightnessa}" = 'down' ] && [ "${brightness}" != 0 ]; then
		brightness=$((brightness - 1))
	fi

	if [ "${speeda}" = 'up' ] && [ "${speed}" < 3 ]; then
		speed=$((speed + 1))
	elif [ "${speeda}" = 'down' ] && [ "${speed}" > 0 ]; then
		speed=$((speed - 1))
	elif [ "${speeda}" = 'step' ] && [ "${speed}" < 3 ]; then
		speed=$((speed + 1))
	elif [ "${speeda}" = 'step' ] && [ "${speed}" = 3 ]; then
		speed=0
	fi

	if [ "${effecta}" = 'rotate' ]; then
		effect=$((effect + 1))

		if [ "${effect}" != 7 ]; then
			reda=''
			greena=''
			bluea=''
		else
			reda=${red}
			greena=${green}
			bluea=${blue}
		fi

		if [ "${effect}" = 8 ]; then
			effect=0
		fi
	else
		effect=$([ "${effecta}" != "" ] && echo "${effecta}" || echo "${effect}")
	fi

	kblSet $([ "${brightness}" != "" ] && echo "-bs ${brightness}") $([ "${speed}" != "" ] && echo "-s ${speed}") $([ "${effect}" != "" ] && echo "-e ${effect}") $([ "${reda}" != "" ] && echo "-r ${reda}") $([ "${greena}" != "" ] && echo "-g ${greena}") $([ "${bluea}" != "" ] && echo "-b ${bluea}")
}

guiBrightness() {
	guiBrightness=$(zenity --scale --title "ite-829x brightness" --value ${brightness} --max-value=4 --min-value=0)
	brightness=$([ "${guiBrightness}" != "" ] && echo ${guiBrightness} || echo ${brightness})

	kblSet -bs ${brightness}
}

guiSpeed() {
	guiSpeed=$(zenity --scale --title "ite-829x speed" --value ${speed} --max-value=3 --min-value=0)
	speed=$([ "${guiSpeed}" != "" ] && echo ${guiSpeed} || echo ${speed})

	kblSet -s ${speed}
}

guiEffect() {
	guiEffect=$(zenity --list --title "ite-829x effect" --column="ID" --column="Name" \
		"0" "Wave" \
		"1" "Breathe" \
		"2" "Scan" \
		"3" "Blink" \
		"4" "Random" \
		"5" "Ripple" \
		"6" "Snake" \
		"7" "Solid"
	)
	effect=$([ "${guiEffect}" != "" ] && echo ${guiEffect} || echo ${effect})

	kblSet -e ${effect}
}

guiColor() {
	color=$(zenity --color-selection --title "ite-829x color" --color "rgb(${red},${green},${blue})" | sed 's/rgb(//' | sed 's/)//' | xargs)
	if [ "${color}" != "" ]; then
		IFS=',' read -ra color <<< "${color}"
		red=${color[0]}
		green=${color[1]}
		blue=${color[2]}

		kblSet -e ${effect} -r ${red} -g ${green} -b ${blue}
	fi
}

guiMain() {
	effects=("Wave" "Breathe" "Scan" "Blink" "Random" "Ripple" "Snake" "Solid")

	cmd=$(zenity --list --title "ite-829x GUI" --column='Property' --column='Value' \
		"Brightness" ${brightness} \
		"Speed" ${speed} \
		"Effect" ${effects[${effect}]} \
		"Color" "${red}, ${green}, ${blue}" \
		"Save" ""
	)

	case "${cmd}" in
		Brightness)
			guiBrightness
			guiMain
		;;
		Speed)
			guiSpeed
			guiMain
		;;
		Effect)
			guiEffect
			guiMain
		;;
		Color)
			guiColor
			guiMain
		;;
		Save)
			kblSave
		;;
		*)
			kblLoad
			kblSet
		;;
	esac
}

ite829xFind
kblLoad

i=1;
for arg in "${@}"
do
	j=$((i + 1))
	case "${!i}" in
		--load)
			kblSet
		;;
		--set)
			kblSet ${@}
			kblSave
		;;
		--toggle)
			kblToggle ${@}
			kblSave
		;;
		--gui)
			guiMain
		;;
	esac
	i=$((i + 1));
done

exit 0
